modLoader="javafml"
loaderVersion="[36,)"
license="Placeholder"
[[mods]]
modId="project"
version="1.0.0"
displayName="Project"
#logoFile="project.png"
authors="HerrBrandstetter"
description='''
Placeholder
'''
[[dependencies.project]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"
[[dependencies.project]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
